- name: remove app location
  ansible.builtin.file:
    path: "{{app_location}}"
    state: absent

- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: "{{app_location}}"
    state: directory     

- name: download the artifact from nexus
  ansible.builtin.unarchive:
    src: "http://{{ nexus_url }}/repository/{{ component }}/com/expense/{{ component }}/{{ appVersion }}/{{ component }}-{{ appVersion }}.zip"
    dest: "{{ app_location }}"
    remote_src: yes